import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333333",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: "#666666",
    textAlign: "center",
    marginBottom: 50,
    lineHeight: 22,
  },
  buttonContainer: {
    marginVertical: 40,
  },
  emergencyButton: {
    width: width * 0.7,
    height: width * 0.7,
    borderRadius: width * 0.35,
    backgroundColor: "#FF0000",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#FF0000",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 20,
    borderWidth: 8,
    borderColor: "#FFFFFF",
  },
  buttonText: {
    fontSize: 32,
    fontWeight: "900",
    color: "#FFFFFF",
    textAlign: "center",
    textShadowColor: "#000000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  buttonSubText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 8,
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  infoContainer: {
    marginTop: 40,
    alignItems: "center",
  },
  infoText: {
    fontSize: 16,
    color: "#666666",
    marginVertical: 5,
    textAlign: "center",
  },
  permissionButton: {
    backgroundColor: "#FF6600",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 15,
    marginTop: 10,
  },
  permissionButtonText: {
    color: "#FFFFFF",
    fontWeight: "bold",
    fontSize: 14,
  },
  audioPlaybackContainer: {
    marginTop: 30,
    padding: 20,
    backgroundColor: "#F0F8FF",
    borderRadius: 15,
    width: "100%",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DDD",
  },
  audioTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
  },
  audioControls: {
    alignItems: "center",
    marginBottom: 15,
  },
  audioButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 10,
  },
  stopButton: {
    backgroundColor: "#FF5722",
  },
  audioButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  playbackTime: {
    fontSize: 14,
    color: "#666",
    fontFamily: "monospace",
  },
  clearAudioButton: {
    backgroundColor: "#9E9E9E",
    paddingHorizontal: 20,
    paddingVertical: 8,
    borderRadius: 15,
  },
  clearAudioButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  locationContainer: {
    marginTop: 20,
    padding: 15,
    backgroundColor: "#E8F5E8",
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#4CAF50",
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2E7D32",
    marginBottom: 8,
  },
  locationAddress: {
    fontSize: 14,
    color: "#1B5E20",
    textAlign: "center",
    marginBottom: 8,
    fontWeight: "500",
    lineHeight: 18,
  },
  locationCoords: {
    fontSize: 12,
    color: "#388E3C",
    fontFamily: "monospace",
    marginBottom: 4,
  },
  locationAccuracy: {
    fontSize: 11,
    color: "#66BB6A",
    fontStyle: "italic",
  },
  refreshLocationButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 12,
    marginTop: 10,
  },
  refreshLocationButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "bold",
  },
  activeEmergencyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  emergencyActiveTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#FF0000",
    textAlign: "center",
    marginBottom: 40,
    textShadowColor: "#000000",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  recordingIndicator: {
    backgroundColor: "rgba(255, 0, 0, 0.2)",
    borderRadius: 15,
    padding: 20,
    marginVertical: 20,
    borderWidth: 2,
    borderColor: "#FF0000",
  },
  recordingText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FF0000",
    textAlign: "center",
    marginBottom: 10,
  },
  countdownText: {
    fontSize: 36,
    fontWeight: "900",
    color: "#FF0000",
    textAlign: "center",
  },
  sendingContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  sendingText: {
    fontSize: 18,
    color: "#333333",
    marginTop: 10,
    textAlign: "center",
  },
  completedContainer: {
    alignItems: "center",
    marginVertical: 20,
    padding: 20,
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#4CAF50",
  },
  completedText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4CAF50",
    textAlign: "center",
    marginBottom: 15,
  },
  playButton: {
    backgroundColor: "#2196F3",
    paddingHorizontal: 25,
    paddingVertical: 12,
    borderRadius: 20,
    marginBottom: 10,
  },
  playButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  doneButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 30,
    paddingVertical: 10,
    borderRadius: 15,
  },
  doneButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  emergencyInfo: {
    marginVertical: 30,
    alignItems: "center",
  },
  emergencyInfoText: {
    fontSize: 16,
    color: "#333333",
    marginVertical: 5,
    textAlign: "center",
  },
  cancelButton: {
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#333333",
    marginTop: 20,
  },
  cancelButtonText: {
    fontSize: 16,
    color: "#333333",
    fontWeight: "bold",
    textAlign: "center",
  },
});